### ISSUE TITLE
Attribute Error when trying to import petlib.pack

### ISSUE THREAD

**Issue by NullByteSuiteDevs** [gdanezis/petlib#18]
When attempting to import petlib.pack I get the following error:

Support not loading the library to build docs without compiling.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/petlib-0.0.43-py2.7-linux-armv7l.egg/petlib/pack.py", line 32, in <module>
    from .ec import EcGroup, EcPt
  File "/usr/local/lib/python2.7/dist-packages/petlib-0.0.43-py2.7-linux-armv7l.egg/petlib/ec.py", line 2, in <module>
    from .bn import Bn, force_Bn, get_ctx
  File "/usr/local/lib/python2.7/dist-packages/petlib-0.0.43-py2.7-linux-armv7l.egg/petlib/bn.py", line 794, in <module>
    zero = Bn(0)
  File "/usr/local/lib/python2.7/dist-packages/petlib-0.0.43-py2.7-linux-armv7l.egg/petlib/bn.py", line 222, in __init__
    self.bn = _C.BN_new()
AttributeError: 'NoneType' object has no attribute 'BN_new'

I tried following the error put was left puzzled when it came down to _/usr/local/lib/python2.7/dist-packages/petlib-0.0.43-py2.7-linux-armv7l.egg/petlib/_

Can provide debug information as needed.

**Comment by gdanezis** [comment]
Thanks for this bug report -- I notice that you are on an ARM system, which I have never tested against. The most likely reason for the bug is that the C library, built though cffi, has not in fact been built (built errors?/Installation errors?) and thus the _C types are assigned to None as a backup. 

Did you have any luck calling other functions from the library? (I suppose not?)
