### ISSUE TITLE
KeyError: 'OPENSSL_CONF

### ISSUE THREAD

**Issue by yjz1234** [gdanezis/petlib#24]
When I installing  petlib on win,there is an error:
`
  ERROR: Command errored out with exit status 1:
     command: 'd:\python3\python3.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\12711\\AppData\\Local\\Temp\\pip-install-_5s5ibkx\\petlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\12711\\AppData\\Local\\Temp\\pip-install-_5s5ibkx\\petlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\12711\AppData\Local\Temp\pip-install-_5s5ibkx\petlib\pip-egg-info'
         cwd: C:\Users\12711\AppData\Local\Temp\pip-install-_5s5ibkx\petlib\
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\12711\AppData\Local\Temp\pip-install-_5s5ibkx\petlib\setup.py", line 40, in <module>
        zip_safe=False,
      File "d:\python3\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "d:\python3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "d:\python3\lib\site-packages\setuptools\dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "d:\python3\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "d:\python3\lib\site-packages\setuptools\dist.py", line 740, in finalize_options
        ep.load()(self)
      File "d:\python3\lib\site-packages\setuptools\dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "d:\python3\lib\site-packages\cffi\setuptools_ext.py", line 211, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "d:\python3\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "d:\python3\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "petlib/compile.py", line 34, in <module>
        openssl_conf = os.environ["OPENSSL_CONF"]
      File "d:\python3\lib\os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'OPENSSL_CONF'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by chaima99** [comment]
Did you find any solution considering this error? Because I got the same error
